name: "size-limit-action"
description: "size-limit action"
author: "Andres Alvarez <a.alvarez.sor@gmail.com>"
branding:
  icon: "activity"
  color: "green"
inputs:
  github_token:
    required: true
    description: "a github access token"
  build_script:
    required: false
    description: "a custom npm script to build"
  skip_step:
    required: false
    description: 'which step to skip, either "install" or "build"'
  directory:
    required: false
    description: "a custom subdirectory"
  windows_verbatim_arguments:
    required: false
    description: "exec `size-limit` with the option `windowsVerbatimArguments`"
    default: true
  main_branch:
    required: false
    default: master
    description: "The name of the main/protected branch"
  threshold:
    required: false
    default: 0.005
    description: "The percentage threshold for size changes before posting a comment"
runs:
  using: "node12"
  main: "dist/index.js"
